
import React from 'react';
import { 
  Users, FileText, Mail, ArrowUp, 
  ArrowDown, DollarSign, ShoppingCart, 
  Clock, Award, Star 
} from 'lucide-react';
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardHeader, 
  CardTitle 
} from '@/components/ui/card';
import { 
  ChartContainer, 
  ChartTooltip, 
  ChartTooltipContent 
} from '@/components/ui/chart';
import { 
  Bar, 
  BarChart, 
  Line, 
  LineChart, 
  ResponsiveContainer, 
  XAxis, 
  YAxis 
} from 'recharts';
import { Button } from '@/components/ui/button';
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from '@/components/ui/table';

// Mock data for charts and stats
const revenueData = [
  { month: 'Jan', revenue: 12400 },
  { month: 'Feb', revenue: 14500 },
  { month: 'Mar', revenue: 16100 },
  { month: 'Apr', revenue: 14000 },
  { month: 'May', revenue: 21500 },
  { month: 'Jun', revenue: 24000 },
  { month: 'Jul', revenue: 23000 },
  { month: 'Aug', revenue: 25200 },
  { month: 'Sep', revenue: 27800 },
  { month: 'Oct', revenue: 29600 },
  { month: 'Nov', revenue: 32000 },
  { month: 'Dec', revenue: 34500 },
];

const userActivityData = [
  { day: 'Mon', active: 450 },
  { day: 'Tue', active: 520 },
  { day: 'Wed', active: 670 },
  { day: 'Thu', active: 610 },
  { day: 'Fri', active: 580 },
  { day: 'Sat', active: 420 },
  { day: 'Sun', active: 350 },
];

const recentSignups = [
  { id: 1, name: 'Alex Johnson', email: 'alex@example.com', country: 'United States', plan: 'Premium', date: '2023-11-05' },
  { id: 2, name: 'Sara Williams', email: 'sara@example.com', country: 'Canada', plan: 'Basic', date: '2023-11-04' },
  { id: 3, name: 'Raj Patel', email: 'raj@example.com', country: 'India', plan: 'Premium', date: '2023-11-04' },
  { id: 4, name: 'Emma Chen', email: 'emma@example.com', country: 'Australia', plan: 'Basic', date: '2023-11-03' },
  { id: 5, name: 'Luis Rodriguez', email: 'luis@example.com', country: 'Mexico', plan: 'Premium', date: '2023-11-02' },
];

interface StatCardProps {
  title: string;
  value: string | number;
  description: string;
  icon: React.ReactNode;
  trend?: 'up' | 'down' | 'neutral';
  trendValue?: string;
}

const StatCard = ({ title, value, description, icon, trend, trendValue }: StatCardProps) => (
  <Card>
    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
      <CardTitle className="text-sm font-medium">{title}</CardTitle>
      <div className="h-8 w-8 rounded-full bg-primary/10 p-1.5 text-primary">
        {icon}
      </div>
    </CardHeader>
    <CardContent>
      <div className="text-2xl font-bold">{value}</div>
      <p className="text-xs text-muted-foreground">{description}</p>
      {trend && (
        <div className={`flex items-center text-xs mt-2 ${
          trend === 'up' 
            ? 'text-green-500' 
            : trend === 'down' 
              ? 'text-red-500' 
              : 'text-muted-foreground'
        }`}>
          {trend === 'up' ? (
            <ArrowUp className="mr-1 h-3 w-3" />
          ) : trend === 'down' ? (
            <ArrowDown className="mr-1 h-3 w-3" />
          ) : null}
          {trendValue}
        </div>
      )}
    </CardContent>
  </Card>
);

const AdminOverview = () => {
  return (
    <div className="space-y-8">
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <StatCard
          title="Total Users"
          value="12,453"
          description="Total registered accounts"
          icon={<Users className="h-5 w-5" />}
          trend="up"
          trendValue="+15% from last month"
        />
        <StatCard
          title="Active Users Today"
          value="1,245"
          description="Logged in in the last 24h"
          icon={<Clock className="h-5 w-5" />}
          trend="up"
          trendValue="+5% from yesterday"
        />
        <StatCard
          title="Total Resumes"
          value="28,379"
          description="Created by all users"
          icon={<FileText className="h-5 w-5" />}
          trend="up"
          trendValue="+12% from last month"
        />
        <StatCard
          title="Cover Letters"
          value="14,892"
          description="Generated by all users"
          icon={<Mail className="h-5 w-5" />}
          trend="up"
          trendValue="+8% from last month"
        />
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <StatCard
          title="Resume Reviews"
          value="8,725"
          description="Uploaded for AI review"
          icon={<Star className="h-5 w-5" />}
          trend="up"
          trendValue="+18% from last month"
        />
        <StatCard
          title="Writing Orders"
          value="345"
          description="Active professional writing orders"
          icon={<Award className="h-5 w-5" />}
          trend="up"
          trendValue="+7% from last month"
        />
        <StatCard
          title="Active Subscriptions"
          value="5,432"
          description="Current paid plans"
          icon={<ShoppingCart className="h-5 w-5" />}
          trend="up"
          trendValue="+10% from last month"
        />
        <StatCard
          title="Monthly Revenue"
          value="$87,490"
          description="For current month"
          icon={<DollarSign className="h-5 w-5" />}
          trend="up"
          trendValue="+22% from last month"
        />
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Card className="col-span-1">
          <CardHeader>
            <CardTitle>Revenue</CardTitle>
            <CardDescription>Monthly revenue over the past year</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="h-80">
              <ChartContainer 
                config={{ 
                  revenue: { color: "hsl(var(--primary))" } 
                }}
              >
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={revenueData}>
                    <XAxis
                      dataKey="month"
                      stroke="#888888"
                      fontSize={12}
                      tickLine={false}
                      axisLine={false}
                    />
                    <YAxis
                      stroke="#888888"
                      fontSize={12}
                      tickLine={false}
                      axisLine={false}
                      tickFormatter={(value) => `$${value}`}
                    />
                    <Bar
                      dataKey="revenue"
                      fill="var(--color-revenue)"
                      radius={[4, 4, 0, 0]}
                    />
                    <ChartTooltip
                      content={
                        <ChartTooltipContent 
                          labelFormatter={(label) => `Month: ${label}`}
                          formatter={(value) => [`$${value.toLocaleString()}`, "Revenue"]}
                        />
                      }
                    />
                  </BarChart>
                </ResponsiveContainer>
              </ChartContainer>
            </div>
          </CardContent>
        </Card>

        <Card className="col-span-1">
          <CardHeader>
            <CardTitle>User Activity</CardTitle>
            <CardDescription>Daily active users over the past week</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="h-80">
              <ChartContainer 
                config={{ 
                  active: { color: "hsl(var(--primary))" }
                }}
              >
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={userActivityData}>
                    <XAxis
                      dataKey="day"
                      stroke="#888888"
                      fontSize={12}
                      tickLine={false}
                      axisLine={false}
                    />
                    <YAxis
                      stroke="#888888"
                      fontSize={12}
                      tickLine={false}
                      axisLine={false}
                    />
                    <Line
                      dataKey="active"
                      stroke="var(--color-active)"
                      strokeWidth={2}
                      dot={{ fill: "var(--color-active)" }}
                    />
                    <ChartTooltip
                      content={
                        <ChartTooltipContent
                          labelFormatter={(label) => `Day: ${label}`}
                          formatter={(value) => [`${value.toLocaleString()} users`, "Active"]}
                        />
                      }
                    />
                  </LineChart>
                </ResponsiveContainer>
              </ChartContainer>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <div className="flex justify-between items-center">
            <div>
              <CardTitle>Recent Signups</CardTitle>
              <CardDescription>
                New users who have registered in the past 5 days
              </CardDescription>
            </div>
            <Button variant="outline">View All</Button>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Email</TableHead>
                <TableHead>Country</TableHead>
                <TableHead>Plan</TableHead>
                <TableHead>Date</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {recentSignups.map((user) => (
                <TableRow key={user.id}>
                  <TableCell className="font-medium">{user.name}</TableCell>
                  <TableCell>{user.email}</TableCell>
                  <TableCell>{user.country}</TableCell>
                  <TableCell>
                    <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold ${
                      user.plan === 'Premium' 
                        ? 'bg-primary text-primary-foreground' 
                        : 'bg-muted text-muted-foreground'
                    }`}>
                      {user.plan}
                    </span>
                  </TableCell>
                  <TableCell>{user.date}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
};

export default AdminOverview;
