
import React from 'react';
import { 
  Users, FileText, Mail, ArrowUp, 
  ArrowDown, DollarSign, ShoppingCart, 
  Clock, Award, Star 
} from 'lucide-react';
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardHeader, 
  CardTitle 
} from '@/components/ui/card';
import { 
  ChartContainer, 
  ChartTooltip, 
  ChartTooltipContent 
} from '@/components/ui/chart';
import { 
  Bar, 
  BarChart, 
  Line, 
  LineChart, 
  ResponsiveContainer, 
  XAxis, 
  YAxis 
} from 'recharts';
import { Button } from '@/components/ui/button';
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from '@/components/ui/table';
import { Skeleton } from '@/components/ui/skeleton';
import { useAdminData } from '@/hooks/useAdminData';
import { RecentSignup, MonthlyRevenue, DailyActivity } from '@/services/supabase/adminService';

interface StatCardProps {
  title: string;
  value: string | number;
  description: string;
  icon: React.ReactNode;
  trend?: 'up' | 'down' | 'neutral';
  trendValue?: string;
  isLoading?: boolean;
}

const StatCard = ({ title, value, description, icon, trend, trendValue, isLoading = false }: StatCardProps) => (
  <Card>
    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
      <CardTitle className="text-sm font-medium">{title}</CardTitle>
      <div className="h-8 w-8 rounded-full bg-primary/10 p-1.5 text-primary">
        {icon}
      </div>
    </CardHeader>
    <CardContent>
      {isLoading ? (
        <Skeleton className="h-8 w-24 mb-2" />
      ) : (
        <div className="text-2xl font-bold">{value}</div>
      )}
      <p className="text-xs text-muted-foreground">{description}</p>
      {trend && !isLoading && (
        <div className={`flex items-center text-xs mt-2 ${
          trend === 'up' 
            ? 'text-green-500' 
            : trend === 'down' 
              ? 'text-red-500' 
              : 'text-muted-foreground'
        }`}>
          {trend === 'up' ? (
            <ArrowUp className="mr-1 h-3 w-3" />
          ) : trend === 'down' ? (
            <ArrowDown className="mr-1 h-3 w-3" />
          ) : null}
          {trendValue}
        </div>
      )}
    </CardContent>
  </Card>
);

const AdminOverview = () => {
  const { dashboardStats, isLoadingStats, refetchStats } = useAdminData();
  
  const revenueData: MonthlyRevenue[] = dashboardStats?.revenueByMonth || [];
  const userActivityData: DailyActivity[] = dashboardStats?.activeUsersByDay || [];
  const recentSignups: RecentSignup[] = dashboardStats?.recentSignups || [];
  
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0
    }).format(amount);
  };
  
  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold">Dashboard Overview</h2>
        <Button variant="outline" onClick={() => refetchStats()}>
          <Clock className="mr-2 h-4 w-4" />
          Refresh Data
        </Button>
      </div>
    
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <StatCard
          title="Total Users"
          value={dashboardStats?.userCount.toLocaleString() || '0'}
          description="Total registered accounts"
          icon={<Users className="h-5 w-5" />}
          trend="up"
          trendValue="+15% from last month"
          isLoading={isLoadingStats}
        />
        <StatCard
          title="Active Users Today"
          value={dashboardStats?.activeUsersCount.toLocaleString() || '0'}
          description="Logged in in the last 24h"
          icon={<Clock className="h-5 w-5" />}
          trend="up"
          trendValue="+5% from yesterday"
          isLoading={isLoadingStats}
        />
        <StatCard
          title="Total Resumes"
          value={dashboardStats?.resumeCount.toLocaleString() || '0'}
          description="Created by all users"
          icon={<FileText className="h-5 w-5" />}
          trend="up"
          trendValue="+12% from last month"
          isLoading={isLoadingStats}
        />
        <StatCard
          title="Cover Letters"
          value={dashboardStats?.coverLetterCount.toLocaleString() || '0'}
          description="Generated by all users"
          icon={<Mail className="h-5 w-5" />}
          trend="up"
          trendValue="+8% from last month"
          isLoading={isLoadingStats}
        />
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <StatCard
          title="Resume Reviews"
          value={dashboardStats?.reviewCount.toLocaleString() || '0'}
          description="Uploaded for AI review"
          icon={<Star className="h-5 w-5" />}
          trend="up"
          trendValue="+18% from last month"
          isLoading={isLoadingStats}
        />
        <StatCard
          title="Writing Orders"
          value={dashboardStats?.writingServiceCount.toLocaleString() || '0'}
          description="Active professional writing orders"
          icon={<Award className="h-5 w-5" />}
          trend="up"
          trendValue="+7% from last month"
          isLoading={isLoadingStats}
        />
        <StatCard
          title="Active Subscriptions"
          value={dashboardStats?.subscriptionCount.toLocaleString() || '0'}
          description="Current paid plans"
          icon={<ShoppingCart className="h-5 w-5" />}
          trend="up"
          trendValue="+10% from last month"
          isLoading={isLoadingStats}
        />
        <StatCard
          title="Monthly Revenue"
          value={formatCurrency(dashboardStats?.totalRevenue || 0)}
          description="For current month"
          icon={<DollarSign className="h-5 w-5" />}
          trend="up"
          trendValue="+22% from last month"
          isLoading={isLoadingStats}
        />
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Card className="col-span-1">
          <CardHeader>
            <CardTitle>Revenue</CardTitle>
            <CardDescription>Monthly revenue over the past year</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="h-80">
              {isLoadingStats ? (
                <div className="flex items-center justify-center h-full">
                  <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full"></div>
                </div>
              ) : (
                <ChartContainer 
                  config={{ 
                    revenue: { color: "hsl(var(--primary))" } 
                  }}
                >
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={revenueData}>
                      <XAxis
                        dataKey="month"
                        stroke="#888888"
                        fontSize={12}
                        tickLine={false}
                        axisLine={false}
                      />
                      <YAxis
                        stroke="#888888"
                        fontSize={12}
                        tickLine={false}
                        axisLine={false}
                        tickFormatter={(value) => `$${value}`}
                      />
                      <Bar
                        dataKey="revenue"
                        fill="var(--color-revenue)"
                        radius={[4, 4, 0, 0]}
                      />
                      <ChartTooltip
                        content={
                          <ChartTooltipContent 
                            labelFormatter={(label) => `Month: ${label}`}
                            formatter={(value) => [`$${value.toLocaleString()}`, "Revenue"]}
                          />
                        }
                      />
                    </BarChart>
                  </ResponsiveContainer>
                </ChartContainer>
              )}
            </div>
          </CardContent>
        </Card>

        <Card className="col-span-1">
          <CardHeader>
            <CardTitle>User Activity</CardTitle>
            <CardDescription>Daily active users over the past week</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="h-80">
              {isLoadingStats ? (
                <div className="flex items-center justify-center h-full">
                  <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full"></div>
                </div>
              ) : (
                <ChartContainer 
                  config={{ 
                    active: { color: "hsl(var(--primary))" }
                  }}
                >
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={userActivityData}>
                      <XAxis
                        dataKey="day"
                        stroke="#888888"
                        fontSize={12}
                        tickLine={false}
                        axisLine={false}
                      />
                      <YAxis
                        stroke="#888888"
                        fontSize={12}
                        tickLine={false}
                        axisLine={false}
                      />
                      <Line
                        dataKey="active"
                        stroke="var(--color-active)"
                        strokeWidth={2}
                        dot={{ fill: "var(--color-active)" }}
                      />
                      <ChartTooltip
                        content={
                          <ChartTooltipContent
                            labelFormatter={(label) => `Day: ${label}`}
                            formatter={(value) => [`${value.toLocaleString()} users`, "Active"]}
                          />
                        }
                      />
                    </LineChart>
                  </ResponsiveContainer>
                </ChartContainer>
              )}
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <div className="flex justify-between items-center">
            <div>
              <CardTitle>Recent Signups</CardTitle>
              <CardDescription>
                New users who have registered in the past 5 days
              </CardDescription>
            </div>
            <Button variant="outline">View All</Button>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Email</TableHead>
                <TableHead>Country</TableHead>
                <TableHead>Plan</TableHead>
                <TableHead>Date</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoadingStats ? (
                Array(5).fill(0).map((_, i) => (
                  <TableRow key={i}>
                    <TableCell><Skeleton className="h-5 w-32" /></TableCell>
                    <TableCell><Skeleton className="h-5 w-48" /></TableCell>
                    <TableCell><Skeleton className="h-5 w-24" /></TableCell>
                    <TableCell><Skeleton className="h-5 w-20" /></TableCell>
                    <TableCell><Skeleton className="h-5 w-24" /></TableCell>
                  </TableRow>
                ))
              ) : recentSignups.length > 0 ? (
                recentSignups.map((user) => (
                  <TableRow key={user.id}>
                    <TableCell className="font-medium">{user.name}</TableCell>
                    <TableCell>{user.email}</TableCell>
                    <TableCell>{user.country}</TableCell>
                    <TableCell>
                      <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold ${
                        user.plan === 'Premium' || user.plan === 'Professional'
                          ? 'bg-primary text-primary-foreground' 
                          : 'bg-muted text-muted-foreground'
                      }`}>
                        {user.plan}
                      </span>
                    </TableCell>
                    <TableCell>{new Date(user.date).toLocaleDateString()}</TableCell>
                  </TableRow>
                ))
              ) : (
                <TableRow>
                  <TableCell colSpan={5} className="text-center py-4">No recent signups found</TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
};

export default AdminOverview;
