
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myxltvsyrmmiqmhgdsbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15eGx0dnN5cm1taXFtaGdkc2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDY3MjgsImV4cCI6MjA1OTA4MjcyOH0.c5t304bFp92AgWts7yWxq-69GMv6Rw6r2W828lCsY9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'swiftapply-auth-token',
    }
  }
);
